### PR TITLE
chore: restructured project, compatible with sequelize v6

### PR DESCRIPTION
**Pull request by dededavida**
as requested in issue #4, the project was restructured, compatible with sequelize v6.

### CODE REVIEW

**Comment by dededavida** [comment]
hey guys, I created un repository with as updates mentioned in this commit.

because this repository has been stopped for a long time.

[node-sequelize-noupdate-attributes](https://github.com/diosney/node-sequelize-noupdate-attributes)

**Comment by mmahalwy** [comment]
@daviddossantos feels like you should create a new repo and lib for this? This repo is likely dead.

**Comment by diosney** [comment]
@daviddossantos @mmahalwy Yeah sorry, Life as usual stepped in the road and I had to focus on other things, making me unable to dedicate time to a project I didn't used frequently anymore.

If you wanna be promoted to manage this repo just tell me, I will be more than happy to see that even a simple utility like this is maintained and useful for other people.

**Comment by xzyfer** [comment]
@daviddossantos out of curiosity what exactly wasn't compatible with sequelize v6? The changes in this restructure appear to be semantically equivalent.

**Comment by dededavida** [comment]
hello guys, it's been so long since I did this that I don't remember anymore.

I will close this pull request.

**Pull request closed without merging**
