### PR TITLE
Fix for sequelize >5.19

### PR DESCRIPTION
**Pull request by DanielOverdevestPZH**
Error: TypeError: sequelize.ValidationError is not a constructor
Solved importing class Sequelize and get constructor from there instead of sequelize (without capital)

### CODE REVIEW

**Comment by DanielOverdevestPZH** [comment]
https://github.com/diosney/node-sequelize-noupdate-attributes/issues/4

**Comment by DanielOverdevestPZH** [comment]
@diosney any chance to look at my PR?

**Comment by diosney** [comment]
Merged.

Sorry it took too long, in a couple of days I should publish a new version after I do a quick refresher.

**Comment by DanielOverdevestPZH** [comment]
@diosney thanks, it's still relevant!

**Pull request merged**
